name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  dartz: ^0.10.0
  sqflite_sqlcipher: ^2.1.1
  cached_network_image: ^3.1.0
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  flutter_zoom_drawer: ^3.0.2
  encrypt: ^5.0.1
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

