// Mocks generated by Mockito 5.3.0 from annotations
// in tv_series/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i14;

import 'package:core/core.dart' as _i12;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/src/widgets/navigator.dart' as _i16;
import 'package:flutter/src/widgets/routes.dart' as _i15;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i11;
import 'package:tv_series/data/datasources/db/tv_database_helper.dart' as _i10;
import 'package:tv_series/domain/entities/tv.dart' as _i7;
import 'package:tv_series/domain/entities/tv_detail.dart' as _i8;
import 'package:tv_series/domain/entities/tv_season_detail.dart' as _i9;
import 'package:tv_series/tv_series.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvDetailResponse {
  _FakeTvDetailResponse_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvSeasonDetailResponse_2 extends _i1.SmartFake
    implements _i3.TvSeasonDetailResponse {
  _FakeTvSeasonDetailResponse_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i3.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>> getOnAirTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getOnAirTvSeries, []),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Tv>>(
                  this, Invocation.method(#getOnAirTvSeries, [])))) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>> getPopularTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvSeries, []),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Tv>>(
                  this, Invocation.method(#getPopularTvSeries, [])))) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>> getTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Tv>>(
                  this, Invocation.method(#getTopRatedTvSeries, [])))) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, _i8.TvDetail>>.value(
              _FakeEither_0<_i6.Failure, _i8.TvDetail>(
                  this, Invocation.method(#getTvDetail, [id])))) as _i5
          .Future<_i2.Either<_i6.Failure, _i8.TvDetail>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>> getTvRecommendation(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendation, [id]),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Tv>>(
                  this, Invocation.method(#getTvRecommendation, [id])))) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.TvSeasonDetail>> getTvSeasonDetail(
          int? tvId, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getTvSeasonDetail, [tvId, seasonNumber]),
              returnValue:
                  _i5.Future<_i2.Either<_i6.Failure, _i9.TvSeasonDetail>>.value(
                      _FakeEither_0<_i6.Failure, _i9.TvSeasonDetail>(this,
                          Invocation.method(#getTvSeasonDetail, [tvId, seasonNumber]))))
          as _i5.Future<_i2.Either<_i6.Failure, _i9.TvSeasonDetail>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>> searchTvSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Tv>>(
                  this, Invocation.method(#searchTvSeries, [query])))) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> saveWatchlist(_i8.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tv]),
              returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
                  _FakeEither_0<_i6.Failure, String>(
                      this, Invocation.method(#saveWatchlist, [tv]))))
          as _i5.Future<_i2.Either<_i6.Failure, String>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> removeWatchlist(
          _i8.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
              returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
                  _FakeEither_0<_i6.Failure, String>(
                      this, Invocation.method(#removeWatchlist, [tv]))))
          as _i5.Future<_i2.Either<_i6.Failure, String>>);
  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: _i5.Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvSeries, []),
          returnValue: _i5.Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>.value(
              _FakeEither_0<_i6.Failure, List<_i7.Tv>>(
                  this, Invocation.method(#getWatchlistTvSeries, [])))) as _i5
          .Future<_i2.Either<_i6.Failure, List<_i7.Tv>>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i3.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i3.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [tv]),
          returnValue: _i5.Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> removeWatchlist(_i3.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
          returnValue: _i5.Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i3.TvTable?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: _i5.Future<_i3.TvTable?>.value())
          as _i5.Future<_i3.TvTable?>);
  @override
  _i5.Future<List<_i3.TvTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvTable>>.value(<_i3.TvTable>[]))
          as _i5.Future<List<_i3.TvTable>>);
  @override
  _i5.Future<void> cacheOnAirTvSeries(List<_i3.TvTable>? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#cacheOnAirTvSeries, [tvSeries]),
              returnValue: _i5.Future<void>.value(),
              returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);
  @override
  _i5.Future<List<_i3.TvTable>> getCachedOnAirTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getCachedOnAirTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvTable>>.value(<_i3.TvTable>[]))
          as _i5.Future<List<_i3.TvTable>>);
  @override
  _i5.Future<void> cachePopularTvSeries(List<_i3.TvTable>? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#cachePopularTvSeries, [tvSeries]),
              returnValue: _i5.Future<void>.value(),
              returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);
  @override
  _i5.Future<List<_i3.TvTable>> getCachedPopularTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getCachedPopularTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvTable>>.value(<_i3.TvTable>[]))
          as _i5.Future<List<_i3.TvTable>>);
  @override
  _i5.Future<void> cacheTopRatedTvSeries(List<_i3.TvTable>? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#cacheTopRatedTvSeries, [tvSeries]),
              returnValue: _i5.Future<void>.value(),
              returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);
  @override
  _i5.Future<List<_i3.TvTable>> getCachedTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getCachedTopRatedTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvTable>>.value(<_i3.TvTable>[]))
          as _i5.Future<List<_i3.TvTable>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i3.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TvModel>> getOnAirTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getOnAirTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]))
          as _i5.Future<List<_i3.TvModel>>);
  @override
  _i5.Future<List<_i3.TvModel>> getPopularTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]))
          as _i5.Future<List<_i3.TvModel>>);
  @override
  _i5.Future<List<_i3.TvModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
              returnValue: _i5.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]))
          as _i5.Future<List<_i3.TvModel>>);
  @override
  _i5.Future<_i3.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue: _i5.Future<_i3.TvDetailResponse>.value(
                  _FakeTvDetailResponse_1(
                      this, Invocation.method(#getTvDetail, [id]))))
          as _i5.Future<_i3.TvDetailResponse>);
  @override
  _i5.Future<List<_i3.TvModel>> getTvRecommendation(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendation, [id]),
              returnValue: _i5.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]))
          as _i5.Future<List<_i3.TvModel>>);
  @override
  _i5.Future<_i3.TvSeasonDetailResponse> getTvSeasonDetail(
          int? tvId, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getTvSeasonDetail, [tvId, seasonNumber]),
              returnValue: _i5.Future<_i3.TvSeasonDetailResponse>.value(
                  _FakeTvSeasonDetailResponse_2(
                      this,
                      Invocation.method(
                          #getTvSeasonDetail, [tvId, seasonNumber]))))
          as _i5.Future<_i3.TvSeasonDetailResponse>);
  @override
  _i5.Future<List<_i3.TvModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
              returnValue: _i5.Future<List<_i3.TvModel>>.value(<_i3.TvModel>[]))
          as _i5.Future<List<_i3.TvModel>>);
}

/// A class which mocks [TvDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDatabaseHelper extends _i1.Mock implements _i10.TvDatabaseHelper {
  MockTvDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i11.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: _i5.Future<_i11.Database?>.value())
          as _i5.Future<_i11.Database?>);
  @override
  _i5.Future<int> insertTvWatchlist(_i3.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchlist, [tv]),
          returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> removeTvWatchlist(_i3.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [tv]),
          returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: _i5.Future<Map<String, dynamic>?>.value())
          as _i5.Future<Map<String, dynamic>?>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvSeries, []),
              returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
  @override
  _i5.Future<void> insertTvCacheTransaction(
          List<_i3.TvTable>? tvSeries, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertTvCacheTransaction, [tvSeries, category]),
          returnValue: _i5.Future<void>.value(),
          returnValueForMissingStub:
              _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getCacheTvSeries(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheTvSeries, [category]),
              returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
  @override
  _i5.Future<int> clearTvSeriesCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearTvSeriesCache, [category]),
          returnValue: _i5.Future<int>.value(0)) as _i5.Future<int>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i12.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: _i5.Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_3(
                  this, Invocation.method(#head, [url], {#headers: headers}))))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_3(
                  this, Invocation.method(#get, [url], {#headers: headers}))))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i13.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#post, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_3(
                  this,
                  Invocation.method(#post, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i13.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#put, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_3(
                  this,
                  Invocation.method(#put, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i13.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#patch, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_3(
                  this,
                  Invocation.method(#patch, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i13.Encoding? encoding}) =>
      (super
          .noSuchMethod(Invocation.method(#delete, [url], {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_3(
                  this,
                  Invocation.method(#delete, [
                    url
                  ], {
                    #headers: headers,
                    #body: body,
                    #encoding: encoding
                  })))) as _i5.Future<_i4.Response>);
  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: _i5.Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i14.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: _i5.Future<_i14.Uint8List>.value(_i14.Uint8List(0)))
          as _i5.Future<_i14.Uint8List>);
  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: _i5.Future<_i4.StreamedResponse>.value(
                  _FakeStreamedResponse_4(
                      this, Invocation.method(#send, [request]))))
          as _i5.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [RouteObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteObserver extends _i1.Mock
    implements _i15.RouteObserver<_i15.ModalRoute<dynamic>> {
  @override
  bool debugObservingRoute(_i15.ModalRoute<dynamic>? route) =>
      (super.noSuchMethod(Invocation.method(#debugObservingRoute, [route]),
          returnValue: false) as bool);
  @override
  void subscribe(
          _i15.RouteAware? routeAware, _i15.ModalRoute<dynamic>? route) =>
      super.noSuchMethod(Invocation.method(#subscribe, [routeAware, route]),
          returnValueForMissingStub: null);
  @override
  void unsubscribe(_i15.RouteAware? routeAware) =>
      super.noSuchMethod(Invocation.method(#unsubscribe, [routeAware]),
          returnValueForMissingStub: null);
  @override
  void didPop(_i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didPush(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i16.Route<dynamic>? newRoute, _i16.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}
